# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='Empty', max_length=100, verbose_name='path')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
