# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('the_review', models.CharField(max_length=500, verbose_name='the review')),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
