# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='description')),
                ('list_of_advantages', models.CharField(blank=True, max_length=1000, verbose_name='list of advantages')),
                ('last_words', models.CharField(blank=True, max_length=500, verbose_name='last words')),
                ('date_start', models.DateTimeField(verbose_name='date start')),
                ('date_end', models.DateTimeField(verbose_name='date end')),
            ],
        ),
    ]
